CREATE TABLE [dbo].[DimNivel](
	[Id_Nivel] [int] NOT NULL,
	[Nivel] [varchar](10) NULL,
 CONSTRAINT [PK_DimNivel] PRIMARY KEY CLUSTERED 
(
	[Id_Nivel] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 