CREATE TABLE [dbo].[DimArea](
	[Id_Area] [int] NOT NULL CONSTRAINT [DF_DIMArea_Id_Area]  DEFAULT (NEXT VALUE FOR [dbo].[Seq_Dim_Area]),
	[DescripcionArea] [varchar](60) NULL,
 CONSTRAINT [PK_DIMArea] PRIMARY KEY CLUSTERED 
(
	[Id_Area] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
)
